//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOURA_AGENDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agendum
    {
        public int ID { get; set; }
        public string NOME { get; set; }
        public string SOBRENOME { get; set; }
        public string TELEFONE_RESIDENCIAL { get; set; }
        public string CELULAR_PRINCIPAL { get; set; }
        public string CELULAR_RECADOS { get; set; }
        public string ENDERECO { get; set; }
        public string NUMERO { get; set; }
        public string BAIRRO { get; set; }
        public string CIDADE { get; set; }
        public string ESTADO { get; set; }
    }
}
